title: Halo Flashpoint Reference
description: A small reference site for the Halo Flashpoint game
theme: just-the-docs

url: https://majors8908.github.io/flashpoint_reference/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
